services:
  db:
    image: postgres:16
    container_name: tasktracker-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - tasktracker_pgdata:/var/lib/postgresql/data

volumes:
  tasktracker_pgdata: